### ISSUE TITLE
Training my own dataset, and pretrained model link

### ISSUE THREAD

**Issue by ghost** [kasimebrahim/instance_segmentation#1]
@kasimebrahim 
Thank you for your hard work,

- Upload your pretrained model so that i can test.
- For training, how should the dataset look, a sample of the dataset would be great.
- I have a dataset with icdar 2015 format (x1,y1,x2,y2,x3,y3,x4,y4), [example.zip](https://github.com/kasimebrahim/instance_segmentation/files/4031440/example.zip)
how can I train such dataset?

**Comment by kasimebrahim** [comment]
Hi @deepseek,
You can get a pre-trained model and a dataset under releases. https://github.com/kasimebrahim/instance_segmentation/releases
As for training on a different dataset, It is pretty easy you just have to create a class extending `utils.Dataset` and override a few methods. mainly to setup the annotations and the bounding boxes. You can find two examples in Loader.py https://github.com/kasimebrahim/instance_segmentation/blob/master/Loader.py
